name: CHECK FoezPC # TODO

on:
  push:
    branches: [ "main" ]

jobs:
  CHECK:
  
    runs-on: FoezPC # TODO

    steps:
    - uses: actions/checkout@v4

    - name: CHECK
      shell: bash
      run:
        bash dependency_check.sh FoezPC # TODO
        
